/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as NewRouteImport } from './routes/new'
import { Route as ImportRouteImport } from './routes/import'
import { Route as BankRouteImport } from './routes/bank'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyDeckIdRouteImport } from './routes/study.$deckId'
import { Route as DeckDeckIdEditRouteImport } from './routes/deck.$deckId.edit'

const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRoute = BankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyDeckIdRoute = StudyDeckIdRouteImport.update({
  id: '/study/$deckId',
  path: '/study/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdEditRoute = DeckDeckIdEditRouteImport.update({
  id: '/deck/$deckId/edit',
  path: '/deck/$deckId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/import': typeof ImportRoute
  '/new': typeof NewRoute
  '/reels': typeof ReelsRoute
  '/study/$deckId': typeof StudyDeckIdRoute
  '/deck/$deckId/edit': typeof DeckDeckIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/import': typeof ImportRoute
  '/new': typeof NewRoute
  '/reels': typeof ReelsRoute
  '/study/$deckId': typeof StudyDeckIdRoute
  '/deck/$deckId/edit': typeof DeckDeckIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/import': typeof ImportRoute
  '/new': typeof NewRoute
  '/reels': typeof ReelsRoute
  '/study/$deckId': typeof StudyDeckIdRoute
  '/deck/$deckId/edit': typeof DeckDeckIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bank'
    | '/import'
    | '/new'
    | '/reels'
    | '/study/$deckId'
    | '/deck/$deckId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bank'
    | '/import'
    | '/new'
    | '/reels'
    | '/study/$deckId'
    | '/deck/$deckId/edit'
  id:
    | '__root__'
    | '/'
    | '/bank'
    | '/import'
    | '/new'
    | '/reels'
    | '/study/$deckId'
    | '/deck/$deckId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankRoute: typeof BankRoute
  ImportRoute: typeof ImportRoute
  NewRoute: typeof NewRoute
  ReelsRoute: typeof ReelsRoute
  StudyDeckIdRoute: typeof StudyDeckIdRoute
  DeckDeckIdEditRoute: typeof DeckDeckIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$deckId': {
      id: '/study/$deckId'
      path: '/study/$deckId'
      fullPath: '/study/$deckId'
      preLoaderRoute: typeof StudyDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId/edit': {
      id: '/deck/$deckId/edit'
      path: '/deck/$deckId/edit'
      fullPath: '/deck/$deckId/edit'
      preLoaderRoute: typeof DeckDeckIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankRoute: BankRoute,
  ImportRoute: ImportRoute,
  NewRoute: NewRoute,
  ReelsRoute: ReelsRoute,
  StudyDeckIdRoute: StudyDeckIdRoute,
  DeckDeckIdEditRoute: DeckDeckIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
